### ISSUE TITLE
ERROR. Doesn't seem to be a video

### ISSUE THREAD

**Issue by Divide-By-0** [Panopto-Video-DL/Panopto-Video-DL-lib#1]
On a Panopto site + video that uses hls, I'm unable to download because I get this error.

**Comment by pizidavi** [comment]
Can you give me the link? Or at least the last 15 character

**Comment by ratnesh1729** [comment]
an example = https://mit.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=98ad6f9e-bac1-46d5-89af-af1300d782c2

**Comment by pizidavi** [comment]
@ratnesh1729  Remember that you have to use the link that is automatically copied from [Panopto-Video-DL-browser](https://github.com/Panopto-Video-DL/Panopto-Video-DL-browser) 
Please follow the [Wiki](https://github.com/Panopto-Video-DL/Panopto-Video-DL/wiki/Installation-on-Windows)
